### ISSUE TITLE
setupDecompWorkspace

### ISSUE THREAD

**Issue by ImFabulous** [DxxxxY/1.8.9ForgeTemplate#1]
when I try to run it in Intellij it gives me this error
"Executing 'setupDecompWorkspace'...

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\M.T.P\AppData\Local\Temp\ijresolvers.gradle' line: 339

* What went wrong:
A problem occurred evaluating initialization script.
> No signature of method: org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.whenReady() is applicable for argument types: (SetupUtpTestResultListenerAction) values: [SetupUtpTestResultListenerAction@7b5d65f2]
Possible solutions: whenReady(groovy.lang.Closure)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.12 secs
Execution finished 'setupDecompWorkspace'.
"

**Comment by dxxxxy** [comment]
Hmm, I can't seem to replicate your issue with a clean setup. Can you provide java and gradle version?

**Comment by ImFabulous** [comment]
gradle 3.0
java jdk 1.8.0_333

**Comment by ImFabulous** [comment]
Also when I imported the project give me this error

Unsupported Gradle. 
The project uses Gradle 2.7 which is incompatible with IntelliJ IDEA 2021.3.3.

Possible solution:
 - Upgrade Gradle wrapper to 3.0 version and re-import the project

**Comment by dxxxxy** [comment]
Try to change to **3.1** in `gradle/wrapper/gradle-wrapper.properties` in your workspace. Might be a rare bug with IntelliJ.

**Comment by ImFabulous** [comment]
there is no such file there
