### ISSUE TITLE
Outdated Version For ForgeGradle 

### ISSUE THREAD

**Issue by Minty569** [DxxxxY/1.8.9ForgeTemplate#3]
I'm unsure why this isn't working the steps say to use version 3.1 of forgegradle which I have but then when I go to run it it says "unsuported version of ForgeGradle" I'm just very confused probs doesn't help its entering the early hours of the morning.  
![2022-10-22 23_55_51-Window](https://user-images.githubusercontent.com/106637473/197340180-6b4bb23b-b7a8-4549-8864-7fe5d1a08afc.png)

**Comment by Minty569** [comment]
![2022-10-22 23_57_43-Window](https://user-images.githubusercontent.com/106637473/197340242-0e57507c-6416-47c2-a41a-0e988b2b54fb.png)

**Comment by dxxxxy** [comment]
This isn't an issue, just a warning. Although I prefer staying on the older one because I don't have issues with it.

**Comment by Minty569** [comment]
Ohh ite thanks man.
