### ISSUE TITLE
mcmod.info not loading

### ISSUE THREAD

**Issue by ghost** [DxxxxY/1.8.9ForgeTemplate#4]
the mod doesnt have any info lol

**Comment by dxxxxy** [comment]
This shouldn't happen. Provide more details.

**Comment by ghost** [comment]
> This shouldn't happen. Provide more details.

uh ok
```
[{
  "modid": "test",
  "name": "test",
  "description": "testmod ",
  "version": "${version}",
  "mcversion": "${mcversion}",
  "url": "",
  "updateUrl": "",
  "authorList": ["zxxxxo"],
  "credits": "noone yet",
  "logoFile": "assets/logo.png",
  "screenshots": [],
  "dependencies": []
}]
```

is the mcmod.info file

```
buildscript {
    repositories {
        //new forge repository
        maven { url "https://maven.minecraftforge.net" }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT"
    }
}

plugins {
    id "java"
    id "com.github.johnrengelman.shadow" version "2.0.4"
}

apply plugin: "net.minecraftforge.gradle.forge"

version = "0.0.0"
group = "zxxxxo.studio" //http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "test" //name of the output jar

sourceCompatibility = targetCompatibility = 1.8 //using java 8
compileJava.options.encoding = "UTF-8"

minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "run"
    mappings = "stable_22" //mappings for 1.8.9
    makeObfSourceJar = false //disable creation of sources jar
}

configurations {
    shade
    compile.extendsFrom(shade)
}

repositories {
    //repos for libraries (not gradle plugins)
    //example:
    //maven { url "https://repo.dreamys.studio/" }
}

dependencies {
    //shade will bundle your library to the output jar
    //your libraries will be accessible outside of intellij
    //example:
    //shade "studio.dreamys:libSkyblock:1.1.1"

    //compile will make your library available only in this dev environment
    //your libraries wont be accessible outside of intellij
    //example:
    //compile "studio.dreamys:libSkyblock:1.1.1"
}

processResources {
    //this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    //replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"

        //replace version and mcversion
        expand "version":project.version, "mcversion":project.minecraft.version
    }

    //copy everything else, that"s not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }

    rename '(.+_at.cfg)', 'META-INF/$1'
}

shadowJar {
    dependencies {
        //we remove gson because it belongs to the public api and will break shading
        //exclude(dependency("com.google.code.gson:gson:2.8.6"))
    }
    configurations = [project.configurations.shade]
    duplicatesStrategy DuplicatesStrategy.EXCLUDE //prevent duplicates
    classifier "" //prevent creation of unshadowed jar
}

reobf {
    //reobfuscate the shadowed jar
    shadowJar {}
}

apply plugin: 'idea'
idea {
    module {
        inheritOutputDirs = true
    }
}
subprojects {
    apply plugin: 'idea'
}

task prepareAssets(type: Copy) {
    group = 'build'
    from project.file('src/main/resources')
    into project.file('build/classes/java/main')
}

classes.dependsOn(prepareAssets)
```
is build.gradle

btw im using ur 1.8.9 forgetemplate

my build config is just gradlew build

and this is my java code
```
   @SubscribeEvent
    public void onFirstPlayerJoin(EntityJoinWorldEvent e) {
        Minecraft.getMinecraft().thePlayer.addChatMessage(new ChatComponentText("This works"));
    }
```

idk what i did wrong

**Comment by ghost** [comment]
im using intellj community 2022.3.2, and ur template presets

**Comment by ghost** [comment]
oh wow our usernames are so similar

**Comment by ghost** [comment]
doing this

> You should add CopyResources from [#artifacts](https://github.com/DxxxxY/1.8.9ForgeTemplate#artifacts) as a Task before launch and drag it in front of build.


returns duplicate entry even tho i did the clean thingie

**Comment by ghost** [comment]
> This will create the run configurations.
Note: you will need to change the classpath module to .main


also what does this mean

**Comment by dxxxxy** [comment]
@zxxxxo 
My apologies for the delay, I was working out.

I've replicated your code, what I've noticed is that the `MODID` supplied to the `@Mod` annotation should be the same as in the `mcmod.info`. When it is set to test as shown below, the mod info is working as intented.
```java
@Mod(modid = ExampleMod.MODID, version = ExampleMod.VERSION)
public class ExampleMod {
    public static final String MODID = "test";
    public static final String VERSION = "1.0";
```

> oh wow our usernames are so similar

Yes.



> doing this
> 
> > You should add CopyResources from [#artifacts](https://github.com/DxxxxY/1.8.9ForgeTemplate#artifacts) as a Task before launch and drag it in front of build.
> 
> returns duplicate entry even tho i did the clean thingie

This is because you added the `prepareAssets` task in the `build.gradle` at the end. The artifact behaves the same way, so you have twice the effect. 

> > This will create the run configurations.
> > Note: you will need to change the classpath module to .main
> 
> also what does this mean

Select this, because weird old issue with Forge Gradle.

![image](https://user-images.githubusercontent.com/42523606/223005249-3f8fab54-3291-4341-842f-54c2bce1f473.png)

Hope your issues are resolved!

**Comment by ghost** [comment]
thx so much ur awsome

**Comment by ghost** [comment]
where is this

> Select this, because weird old issue with Forge Gradle.

**Comment by ghost** [comment]
```
@Mod(modid = test.MODID, useMetadata=true, version = test.VERSION)

public class test {
    public static final String MODID = "test";
    public static final String VERSION = "0.0.0";
```

the mod id was already implemented i forgot to add

**Comment by ghost** [comment]
checking my build folder, every. file from build.gradle to test.java to mcmod.info has version 0.0.0

is 0.0.0 not acceptable?

**Comment by ghost** [comment]
changing version to 0.0 also seems to not work

maybe it has to do with no only zeros?

trying 0.1

**Comment by ghost** [comment]
0.1 works and shows as the mod version but it doesn't update the mcmod.info

**Comment by dxxxxy** [comment]
@zxxxxo I got school right now. In the meantime you could create a repo with your problem so I wouldn't have to waste time replicating it.

**Comment by ghost** [comment]
on my page

**Comment by zxxxxo** [comment]
https://github.com/zxxxxo/ScamShield

**Comment by dxxxxy** [comment]
@zxxxxo My apologies for the delay once again.
Since there were many changes needed, I've opened a pull request. Please feel free to look it over.

https://github.com/zxxxxo/ScamShield/pull/1
